query Category($id: ID!) {
  category(id: $id) {
    id
    name
    products {
      id
      name
      description
      price
      weight_units
      size_units
      color
      material
      size
      weight
      image {
        url
      }
    }
  }
}
